import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/Navbar";

import { SiteFooter } from "@/components/SiteFooter";
import { getItems } from "@/app/actions/content";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { getNavbarData } from "@/actions/landing/navbar";

// ... existing imports

export default async function LandingLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const latestPeopleStories = await getItems("people_story", 1);
	const latestPeopleStory = latestPeopleStories[0];
	const navbarData = await getNavbarData();

	return (
		<>
			<Navbar latestPeopleStory={latestPeopleStory} navbarData={navbarData} />
			{children}
			<SiteFooter />
		</>
	);
}
